'use client';

import React, { useState } from 'react';
import { useClinic } from '@/context/ClinicContext';

export default function PatientCheckInPage() {
  const { checkInPatient, staff } = useClinic();
  const [accessCode, setAccessCode] = useState('');
  const [selectedVet, setSelectedVet] = useState(staff[0]?.name || 'Dr. Sarah Smith');
  const [room, setRoom] = useState('Room 1');
  const [reason, setReason] = useState('');
  const [isSuccess, setIsSuccess] = useState(false);
  const [admittedName, setAdmittedName] = useState('Patient');

  const handleCheckIn = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!accessCode.trim()) return;

    const patientName = `Patient (${accessCode.trim().toUpperCase()})`;
    setAdmittedName(patientName);

    await checkInPatient({
      petName: patientName,
      species: 'Canine / Feline',
      ownerName: 'Furr Verified Owner',
      timeArrived: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      assignedVet: selectedVet,
      status: 'In Consultation',
      room,
      reason: reason.trim() || 'General Consultation & Examination',
    });

    setIsSuccess(true);
  };

  const handleEmergencyCheckIn = async () => {
    const emergencyName = `Emergency Patient #${Math.floor(100 + Math.random() * 900)}`;
    setAdmittedName(emergencyName);
    setAccessCode('EMERGENCY');

    await checkInPatient({
      petName: emergencyName,
      species: 'Unknown / Critical',
      ownerName: 'Walk-in (Unregistered)',
      timeArrived: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      assignedVet: 'Emergency Duty Vet',
      status: 'Triage / Vitals',
      room: 'Triage Bay A',
      reason: 'Urgent Emergency Admission',
    });

    setIsSuccess(true);
  };

  return (
    <div className="max-w-4xl space-y-6">
      <div>
        <h1 className="text-3xl font-black text-slate-900 tracking-tight">Patient Intake &amp; Check-In</h1>
        <p className="text-slate-500 text-sm mt-1">
          Scan or enter the owner&apos;s Furr QR code / 6-digit access grant to admit the patient and route to duty staff.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Intake Form */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 mb-4">Patient Admission Form</h2>

          {isSuccess ? (
            <div className="p-6 bg-emerald-50 border border-emerald-200 rounded-xl text-center space-y-3">
              <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto text-xl font-bold">
                ✓
              </div>
              <h3 className="font-bold text-emerald-900 text-lg">{admittedName} Admitted Successfully</h3>
              <p className="text-xs text-emerald-700">
                Grant code <strong>{accessCode.toUpperCase()}</strong> registered. Patient routed to {room} with {selectedVet}.
              </p>
              <button
                onClick={() => {
                  setIsSuccess(false);
                  setAccessCode('');
                  setReason('');
                }}
                className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs px-4 py-2 rounded-lg transition mt-2"
              >
                Intake Another Patient
              </button>
            </div>
          ) : (
            <form onSubmit={handleCheckIn} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Owner Access Grant Code (QR / 6-Char)
                </label>
                <input
                  type="text"
                  placeholder="e.g. A9B2X7"
                  value={accessCode}
                  maxLength={10}
                  onChange={(e) => setAccessCode(e.target.value.toUpperCase())}
                  required
                  className="w-full font-mono uppercase bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-lg font-bold tracking-widest text-slate-900 focus:outline-none focus:ring-2 focus:ring-sky-500"
                />
                <span className="text-[11px] text-slate-400 mt-1 block">
                  Generated by owner in Furr Mobile App &gt; Share Records
                </span>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Assigned Duty Clinician
                </label>
                <select
                  value={selectedVet}
                  onChange={(e) => setSelectedVet(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-sm font-medium text-slate-900 focus:outline-none focus:ring-2 focus:ring-sky-500"
                >
                  {staff.map((s) => (
                    <option key={s.id} value={s.name}>
                      {s.name} ({s.role})
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Exam Room / Bay
                </label>
                <select
                  value={room}
                  onChange={(e) => setRoom(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-sm font-medium text-slate-900 focus:outline-none focus:ring-2 focus:ring-sky-500"
                >
                  <option value="Room 1">Consultation Room 1 (General)</option>
                  <option value="Room 2">Consultation Room 2 (Vaccine / Fast Track)</option>
                  <option value="Triage Bay A">Triage Bay A (Urgent Vitals)</option>
                  <option value="Prep Room B">Prep Room B (Pre-Op Induction)</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Chief Complaint / Reason for Visit
                </label>
                <textarea
                  rows={2}
                  placeholder="e.g. Annual vaccination booster, check minor rash on ear"
                  value={reason}
                  onChange={(e) => setReason(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-3 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-sky-500"
                />
              </div>

              <button
                type="submit"
                className="w-full bg-sky-600 hover:bg-sky-500 text-white font-bold py-3.5 rounded-xl transition text-sm shadow-sm"
              >
                Confirm Admission &amp; Open Record
              </button>
            </form>
          )}
        </div>

        {/* QR Scanner / Quick Guide Box */}
        <div className="space-y-6">
          <div className="bg-slate-900 text-white p-6 rounded-2xl border border-slate-800 shadow-sm space-y-4">
            <span className="text-xs font-black text-sky-400 uppercase tracking-widest">Intake Hardware</span>
            <h3 className="font-bold text-lg">Barcode / 2D Scanner Ready</h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              Standard USB or Bluetooth 2D barcode scanners will automatically enter the 6-character grant code directly into the input field above.
            </p>
            <div className="border border-dashed border-slate-700 rounded-xl p-6 text-center bg-slate-800/40">
              <span className="text-slate-400 text-xs block font-mono">Ready for optical scan...</span>
            </div>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-3">
            <h4 className="font-bold text-slate-900 text-sm">Emergency / Unregistered Intake</h4>
            <p className="text-xs text-slate-500 leading-relaxed">
              If an emergency patient arrives without a Furr account, click below to generate an immediate temporary clinic chart.
            </p>
            <button
              onClick={handleEmergencyCheckIn}
              className="text-xs font-bold text-red-700 bg-red-50 hover:bg-red-100 border border-red-200 px-4 py-2.5 rounded-lg transition w-full"
            >
              🚨 Create Temporary Emergency Chart
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
